[project]
name = "repl-nix-accessbotai"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "flask>=3.1.0",
    "flask-login>=0.6.3",
    "flask-sqlalchemy>=3.1.1",
    "flask-wtf>=1.2.2",
    "openai>=1.55.0",
    "psycopg2-binary>=2.9.10",
    "werkzeug",
    "sqlalchemy",
    "google-cloud-core>=2.4.1",
    "google-auth>=2.36.0",
    "pdfminer-six>=20240706",
    "spacy>=3.8.2",
    "pytesseract>=0.3.13",
    "python-magic>=0.4.27",
]
