# Simplified Cartography Configuration for Local Development

neo4j:
  uri: ${NEO4J_URI:-bolt://localhost:7687}
  auth:
    username: ${NEO4J_USER:-neo4j}
    password: ${NEO4J_PASSWORD:-password}
  options:
    max_connection_lifetime: 3600
    max_connection_pool_size: 50
    connection_timeout: 30
    connection_acquisition_timeout: 60
    trust: TRUST_ALL_CERTIFICATES

sync:
  # Sync configuration
  type: INCREMENTAL
  concurrency: 10
  update_tag: UPDATE_TAG
  batch_size: 1000
  
  # Module configuration
  modules:
    - cartography.intel.gcp:
        enabled: true
        options:
          projects: ["*"]
          compute:
            enabled: true
            instance_tags: true
          storage:
            enabled: true
          iam:
            enabled: true
            service_accounts: true
          asset:
            enabled: true
            asset_types:
              - compute.googleapis.com/Instance
              - compute.googleapis.com/Network
              - storage.googleapis.com/Bucket
              - iam.googleapis.com/ServiceAccount

# Logging configuration
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      enabled: true
      format: '%(levelname)s: %(message)s'
